# 工作流程名称
name: slc exe

on:
    # 允许用户手动触发工作流程
    workflow_dispatch:
    # 仓库收到 push 和 pr 时触发工作流程
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

# GITHUB_TOKEN 的权限
permissions:
    contents: read

jobs:
    build:
        # 指定运行环境
        runs-on: windows-latest
        # 任务步骤
        steps:
            # 拉取仓库代码（必须）
            - uses: actions/checkout@v4.1.5
            # 设置 Python 版本
            - name: Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                  python-version: "3.12.3"
                  # 从缓存中安装 pip (跳过下载过程)
                  cache: "pip"
            # pip 安装依赖
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            # 打包 exe
            - name: Package
              run: |
                  pyinstaller --onefile slc.py 
                  pyinstaller --onefile slc.py 
            # 上传结果为 artifact
            - name: Upload results
              uses: actions/upload-artifact@v4.3.3
              with:
                  # 结果名(无论写什么，结果始终是zip最后)
                  name: result
                  # 结果文件（可以是单个文件，多个文件）
                  path: dist
                  # 压缩级别(默认0, 0-9, 0 为不压缩)
                  compression-level: 0
                  # 保留时间(默认90)
                  retention-days: 90
            - name: Upload # 上传
              uses: softprops/action-gh-release@v2 # 使用第三方actions 上传
              if: startsWith(github.ref, 'refs/tags/') # 仅在tag时上传
              with:
                files: dist/result.zip # 上传的文件
