name: slc exe

on:
    workflow_dispatch:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

permissions:
    contents: read

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4.1.5
            - name: Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                  python-version: "3.12.3"
                  cache: "pip"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Package
              run: |
                  pyinstaller --onefile slc.py
            - name: Check package result
              run: |
                  if not exist dist\slc.exe (
                      echo "Packaging failed!"
                      exit /b 1
                  )
            - name: Upload results
              uses: actions/upload-artifact@v4.3.3
              with:
                  name: slc
                  path: dist
                  compression-level: 0
                  retention-days: 90
